// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyjoebosqseywqvxbbtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5am9lYm9zcXNleXdxdnhiYnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyODA2MDEsImV4cCI6MjA1NTg1NjYwMX0.B7QS6XoGieBNBkfygBYb1XCJQGiSWtfou7h6wCQAQsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);